
export const landingUsers: any[] = [
  {
    id: "lu1",
    name: "Alex Morgan",
    email: "alex@fLowboard.app",
    role: "owner",
    joinedDate: "2024-01-15",
    avatarUrl: "",
  },
  {
    id: "lu2",
    name: "Jordan Lee",
    email: "jordan@fLowboard.app",
    role: "admin",
    joinedDate: "2024-02-20",
    avatarUrl: "",
  },
  {
    id: "lu3",
    name: "Sam Rivera",
    email: "sam@fLowboard.app",
    role: "member",
    joinedDate: "2024-03-10",
    avatarUrl: "",
  },
  {
    id: "lu4",
    name: "Taylor Chen",
    email: "taylor@fLowboard.app",
    role: "member",
    joinedDate: "2024-04-05",
    avatarUrl: "",
  },
  {
    id: "lu5",
    name: "Morgan Patel",
    email: "morgan@fLowboard.app",
    role: "member",
    joinedDate: "2024-05-18",
    avatarUrl: "",
  },
];

export const landingLabels: any[] = [
  { id: "ll1", name: "Design", color: "#8b5cf6" },
  { id: "ll2", name: "Frontend", color: "#3b82f6" },
  { id: "ll3", name: "Backend", color: "#10b981" },
  { id: "ll4", name: "Bug", color: "#ef4444" },
  { id: "ll5", name: "Feature", color: "#f59e0b" },
  { id: "ll6", name: "Research", color: "#06b6d4" },
];

export const landingColumns: any[] = [
  {
    id: "lc1",
    name: "Backlog",
    projectId: "lp1",
    position: 0,
    color: "#94a3b8",
  },
  { id: "lc2", name: "To Do", projectId: "lp1", position: 1, color: "#64748b" },
  {
    id: "lc3",
    name: "In Progress",
    projectId: "lp1",
    position: 2,
    color: "#3b82f6",
  },
  {
    id: "lc4",
    name: "Review",
    projectId: "lp1",
    position: 3,
    color: "#a855f7",
  },
  { id: "lc5", name: "Done", projectId: "lp1", position: 4, color: "#10b981" },
];

export const landingTasks: any[] = [
  {
    id: "lt1",
    title: "Design new onboarding screens",
    description: "High-fidelity mockups for the 4-step onboarding fLow",
    completed: false,
    status: "in_progress",
    priority: "High",
    backgroundColor: "#3b82f6",
    dueDate: "2025-09-06",
    createdAt: "2025-08-25",
    updatedAt: "2025-09-01",
    projectId: "lp1",
    assigneeId: "lu1",
    labelIds: ["ll1", "ll2"],
    columnId: "lc3",
    position: 0,
  },
  {
    id: "lt2",
    title: "Implement authentication fLow",
    description: "Wire up login, register, and password reset",
    completed: false,
    status: "in_progress",
    priority: "Urgent",
    backgroundColor: "#ef4444",
    dueDate: "2025-09-05",
    createdAt: "2025-08-27",
    updatedAt: "2025-09-01",
    projectId: "lp1",
    assigneeId: "lu4",
    labelIds: ["ll2", "ll3"],
    columnId: "lc3",
    position: 1,
  },
  {
    id: "lt3",
    title: "Set up CI/CD pipeline",
    description: "Configure GitHub Actions for lint, test, and deploy",
    completed: false,
    status: "review",
    priority: "Medium",
    backgroundColor: "#a855f7",
    dueDate: "2025-09-07",
    createdAt: "2025-08-29",
    updatedAt: "2025-09-01",
    projectId: "lp1",
    assigneeId: "lu3",
    labelIds: ["ll3"],
    columnId: "lc4",
    position: 0,
 
  },
  {
    id: "lt4",
    title: "Write API documentation",
    description: "Document all REST endpoints with examples",
    completed: true,
    status: "done",
    priority: "Low",
    backgroundColor: "#10b981",
    dueDate: "2025-08-30",
    createdAt: "2025-08-20",
    updatedAt: "2025-08-30",
    projectId: "lp1",
    assigneeId: "lu2",
    labelIds: ["ll6"],
    columnId: "lc5",
    position: 0,
  },
  {
    id: "lt5",
    title: "User testing sessions",
    description: "Run 5 user testing sessions with the new prototype",
    completed: false,
    status: "todo",
    priority: "Medium",
    backgroundColor: "#f59e0b",
    dueDate: "2025-09-09",
    createdAt: "2025-08-28",
    updatedAt: "2025-08-28",
    projectId: "lp1",
    assigneeId: "lu5",
    labelIds: ["ll6", "ll1"],
    columnId: "lc2",
    position: 0,
  },
  {
    id: "lt6",
    title: "Push notification system",
    description: "Add push notifications for task assignments",
    completed: false,
    status: "backlog",
    priority: "Low",
    backgroundColor: "#64748b",
    createdAt: "2025-08-31",
    updatedAt: "2025-08-31",
    projectId: "lp1",
    assigneeId: "lu4",
    labelIds: ["ll3", "ll5"],
    columnId: "lc1",
    position: 0,
  },
  {
    id: "lt7",
    title: "Dark mode polish",
    description: "Review every screen in dark mode and fix contrast",
    completed: false,
    status: "todo",
    priority: "High",
    backgroundColor: "#8b5cf6",
    dueDate: "2025-09-08",
    createdAt: "2025-08-30",
    updatedAt: "2025-08-31",
    projectId: "lp1",
    assigneeId: "lu1",
    labelIds: ["ll1", "ll2"],
    columnId: "lc2",
    position: 1,
  },
  {
    id: "lt8",
    title: "Optimize bundle size",
    description: "Audit dependencies and reduce initial JS bundle by 30%",
    completed: true,
    status: "done",
    priority: "Medium",
    backgroundColor: "#10b981",
    dueDate: "2025-08-26",
    createdAt: "2025-08-15",
    updatedAt: "2025-08-26",
    projectId: "lp1",
    assigneeId: "lu3",
    labelIds: ["ll3"],
    columnId: "lc5",
    position: 1,
  },
];
