import type {
  User, Project, Task, Column, Label, Notification, Activity, Workspace, WorkspaceMember,
} from './types';

export const currentUser: User = {
  id: 'u1',
  name: 'Alex Morgan',
  email: 'alex.morgan@flowboard.app',
  role: 'owner',
  bio: 'Product designer turned project lead. I build teams that ship.',
  avatarUrl: '',
  joinedDate: '2023-01-15',
  age: 32,
};

export const users: User[] = [
  currentUser,
  { id: 'u2', name: 'Jordan Lee', email: 'jordan.lee@flowboard.app', role: 'admin', joinedDate: '2023-02-20', avatarUrl: '', age: 28 },
  { id: 'u3', name: 'Sam Rivera', email: 'sam.rivera@flowboard.app', role: 'member', joinedDate: '2023-03-10', avatarUrl: '', age: 35 },
  { id: 'u4', name: 'Taylor Chen', email: 'taylor.chen@flowboard.app', role: 'member', joinedDate: '2023-04-05', avatarUrl: '', age: 26 },
  { id: 'u5', name: 'Morgan Patel', email: 'morgan.patel@flowboard.app', role: 'member', joinedDate: '2023-05-18', avatarUrl: '', age: 41 },
  { id: 'u6', name: 'Casey Brooks', email: 'casey.brooks@flowboard.app', role: 'member', joinedDate: '2023-06-22', avatarUrl: '', age: 30 },
  { id: 'u7', name: 'Riley Adams', email: 'riley.adams@flowboard.app', role: 'member', joinedDate: '2023-07-30', avatarUrl: '', age: 33 },
];

export const workspace: Workspace = {
  id: 'w1',
  name: 'Acme Studio',
  logoUrl: '',
  ownerId: 'u1',
  memberIds: ['u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7'],
  createdAt: '2023-01-15',
};

export const workspaces: Workspace[] = [
  workspace,
  { id: 'w2', name: 'Personal', logoUrl: '', ownerId: 'u1', memberIds: ['u1'], createdAt: '2023-01-15' },
  { id: 'w3', name: 'Design Guild', logoUrl: '', ownerId: 'u1', memberIds: ['u1', 'u3', 'u6'], createdAt: '2023-03-01' },
];

export const workspaceMembers: WorkspaceMember[] = [
  { userId: 'u1', workspaceId: 'w1', role: 'owner', joinedDate: '2023-01-15' },
  { userId: 'u2', workspaceId: 'w1', role: 'admin', joinedDate: '2023-02-20' },
  { userId: 'u3', workspaceId: 'w1', role: 'member', joinedDate: '2023-03-10' },
  { userId: 'u4', workspaceId: 'w1', role: 'member', joinedDate: '2023-04-05' },
  { userId: 'u5', workspaceId: 'w1', role: 'member', joinedDate: '2023-05-18' },
  { userId: 'u6', workspaceId: 'w1', role: 'member', joinedDate: '2023-06-22' },
  { userId: 'u7', workspaceId: 'w1', role: 'member', joinedDate: '2023-07-30' },
];

export const labels: Label[] = [
  { id: 'l1', name: 'Design', color: '#8b5cf6' },
  { id: 'l2', name: 'Frontend', color: '#3b82f6' },
  { id: 'l3', name: 'Backend', color: '#10b981' },
  { id: 'l4', name: 'Bug', color: '#ef4444' },
  { id: 'l5', name: 'Feature', color: '#f59e0b' },
  { id: 'l6', name: 'Research', color: '#06b6d4' },
  { id: 'l7', name: 'Docs', color: '#64748b' },
  { id: 'l8', name: 'Marketing', color: '#ec4899' },
];

const now = new Date();
const daysFromNow = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() + n);
  return d.toISOString();
};

export const projects: Project[] = [
  {
    id: 'p1',
    name: 'Mobile App Redesign',
    description: 'Complete overhaul of the iOS and Android app with a fresh design system and improved onboarding flow.',
    status: 'active',
    backgroundColor: '#3b82f6',
    visibility: 'workspace',
    workspaceId: 'w1',
    createdAt: '2024-01-10',
    updatedAt: daysFromNow(-1),
    ownerId: 'u1',
    memberIds: ['u1', 'u2', 'u3', 'u4'],
    favorite: true,
  },
  {
    id: 'p2',
    name: 'Marketing Website',
    description: 'Launch the new marketing site with updated branding, case studies, and a blog.',
    status: 'active',
    backgroundColor: '#ec4899',
    visibility: 'public',
    workspaceId: 'w1',
    createdAt: '2024-02-05',
    updatedAt: daysFromNow(-3),
    ownerId: 'u2',
    memberIds: ['u1', 'u2', 'u5'],
    favorite: true,
  },
  {
    id: 'p3',
    name: 'API Platform v2',
    description: 'Rebuild the core API with GraphQL, rate limiting, and a developer portal.',
    status: 'on_hold',
    backgroundColor: '#10b981',
    visibility: 'private',
    workspaceId: 'w1',
    createdAt: '2024-03-15',
    updatedAt: daysFromNow(-7),
    ownerId: 'u3',
    memberIds: ['u3', 'u4', 'u6'],
    favorite: false,
  },
  {
    id: 'p4',
    name: 'Customer Research',
    description: 'User interviews, surveys, and competitive analysis for Q3 roadmap planning.',
    status: 'active',
    backgroundColor: '#f59e0b',
    visibility: 'workspace',
    workspaceId: 'w1',
    createdAt: '2024-04-01',
    updatedAt: daysFromNow(-2),
    ownerId: 'u1',
    memberIds: ['u1', 'u5', 'u7'],
    favorite: false,
  },
  {
    id: 'p5',
    name: 'Internal Tooling',
    description: 'Dashboards and automation scripts to speed up the whole engineering team.',
    status: 'completed',
    backgroundColor: '#8b5cf6',
    visibility: 'private',
    workspaceId: 'w1',
    createdAt: '2024-05-20',
    updatedAt: daysFromNow(-14),
    ownerId: 'u4',
    memberIds: ['u4', 'u6'],
    favorite: false,
  },
  {
    id: 'p6',
    name: 'Brand Refresh',
    description: 'New visual identity, logo system, and brand guidelines for 2025.',
    status: 'active',
    backgroundColor: '#06b6d4',
    visibility: 'workspace',
    workspaceId: 'w1',
    createdAt: '2024-06-12',
    updatedAt: daysFromNow(-5),
    ownerId: 'u1',
    memberIds: ['u1', 'u2', 'u3', 'u5', 'u7'],
    favorite: true,
  },
];

export const columns: Column[] = [
  { id: 'c1', name: 'Backlog', projectId: 'p1', position: 0, color: '#94a3b8' },
  { id: 'c2', name: 'To Do', projectId: 'p1', position: 1, color: '#64748b' },
  { id: 'c3', name: 'In Progress', projectId: 'p1', position: 2, color: '#3b82f6' },
  { id: 'c4', name: 'Review', projectId: 'p1', position: 3, color: '#a855f7' },
  { id: 'c5', name: 'Done', projectId: 'p1', position: 4, color: '#10b981' },
];

const baseActivity = (type: Activity['type'], userId: string, text: string, daysAgo: number): Activity => ({
  id: `a-${type}-${userId}-${daysAgo}`,
  type,
  userId,
  targetId: 'p1',
  targetType: 'project',
  text,
  createdAt: daysFromNow(-daysAgo),
});

export const tasks: Task[] = [
  {
    id: 't1',
    title: 'Design new onboarding screens',
    description: 'Create high-fidelity mockups for the 4-step onboarding flow including welcome, permissions, and tutorial.',
    completed: false,
    status: 'in_progress',
    priority: 'high',
    backgroundColor: '#3b82f6',
    dueDate: daysFromNow(2),
    createdAt: daysFromNow(-10),
    updatedAt: daysFromNow(-1),
    projectId: 'p1',
    assigneeId: 'u1',
    labelIds: ['l1', 'l2'],
    columnId: 'c3',
    position: 0,
    checklist: [
      { id: 'ch1', text: 'Welcome screen', completed: true },
      { id: 'ch2', text: 'Permissions screen', completed: true },
      { id: 'ch3', text: 'Tutorial overlay', completed: false },
      { id: 'ch4', text: 'Final review with team', completed: false },
    ],
    comments: [
      { id: 'cm1', userId: 'u2', text: 'Love the direction! Can we make the welcome screen a bit more vibrant?', createdAt: daysFromNow(-2) },
      { id: 'cm2', userId: 'u1', text: 'Good call — I will push an updated version today.', createdAt: daysFromNow(-1) },
    ],
    attachments: [
      { id: 'at1', fileName: 'onboarding-v3.fig', fileType: 'figma', fileSize: '2.4 MB' },
      { id: 'at2', fileName: 'brand-guidelines.pdf', fileType: 'pdf', fileSize: '1.1 MB' },
    ],
    activity: [
      baseActivity('task_created', 'u1', 'created this task', 10),
      { id: 'a1', type: 'assigned', userId: 'u1', targetId: 't1', targetType: 'task', text: 'assigned to Alex Morgan', createdAt: daysFromNow(-9) },
      { id: 'a2', type: 'status_changed', userId: 'u1', targetId: 't1', targetType: 'task', text: 'moved to In Progress', createdAt: daysFromNow(-5) },
      { id: 'a3', type: 'commented', userId: 'u2', targetId: 't1', targetType: 'task', text: 'commented on this task', createdAt: daysFromNow(-2) },
    ],
  },
  {
    id: 't2',
    title: 'Implement authentication flow',
    description: 'Wire up login, register, and password reset screens with the backend API.',
    completed: false,
    status: 'in_progress',
    priority: 'urgent',
    backgroundColor: '#ef4444',
    dueDate: daysFromNow(1),
    createdAt: daysFromNow(-8),
    updatedAt: daysFromNow(-1),
    projectId: 'p1',
    assigneeId: 'u4',
    labelIds: ['l2', 'l3'],
    columnId: 'c3',
    position: 1,
    checklist: [
      { id: 'ch5', text: 'Login endpoint', completed: true },
      { id: 'ch6', text: 'Register endpoint', completed: true },
      { id: 'ch7', text: 'Password reset', completed: false },
    ],
    comments: [],
    attachments: [],
    activity: [
      { id: 'a4', type: 'task_created', userId: 'u4', targetId: 't2', targetType: 'task', text: 'created this task', createdAt: daysFromNow(-8) },
    ],
  },
  {
    id: 't3',
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions for lint, test, and deploy on staging and production.',
    completed: false,
    status: 'review',
    priority: 'medium',
    backgroundColor: '#a855f7',
    dueDate: daysFromNow(3),
    createdAt: daysFromNow(-6),
    updatedAt: daysFromNow(-1),
    projectId: 'p1',
    assigneeId: 'u6',
    labelIds: ['l3'],
    columnId: 'c4',
    position: 0,
    checklist: [
      { id: 'ch8', text: 'Lint job', completed: true },
      { id: 'ch9', text: 'Test job', completed: true },
      { id: 'ch10', text: 'Deploy to staging', completed: true },
      { id: 'ch11', text: 'Deploy to production', completed: false },
    ],
    comments: [
      { id: 'cm3', userId: 'u3', text: 'Looks solid. Approve after the production step is gated behind manual confirmation.', createdAt: daysFromNow(-1) },
    ],
    attachments: [],
    activity: [
      { id: 'a5', type: 'task_created', userId: 'u6', targetId: 't3', targetType: 'task', text: 'created this task', createdAt: daysFromNow(-6) },
      { id: 'a6', type: 'status_changed', userId: 'u6', targetId: 't3', targetType: 'task', text: 'moved to Review', createdAt: daysFromNow(-1) },
    ],
  },
  {
    id: 't4',
    title: 'Write API documentation',
    description: 'Document all REST endpoints with examples and OpenAPI spec.',
    completed: true,
    status: 'done',
    priority: 'low',
    backgroundColor: '#10b981',
    dueDate: daysFromNow(-2),
    createdAt: daysFromNow(-12),
    updatedAt: daysFromNow(-2),
    projectId: 'p1',
    assigneeId: 'u3',
    labelIds: ['l7', 'l3'],
    columnId: 'c5',
    position: 0,
    checklist: [
      { id: 'ch12', text: 'Auth endpoints', completed: true },
      { id: 'ch13', text: 'Project endpoints', completed: true },
      { id: 'ch14', text: 'Task endpoints', completed: true },
    ],
    comments: [],
    attachments: [
      { id: 'at3', fileName: 'openapi.yaml', fileType: 'yaml', fileSize: '340 KB' },
    ],
    activity: [
      { id: 'a7', type: 'task_created', userId: 'u3', targetId: 't4', targetType: 'task', text: 'created this task', createdAt: daysFromNow(-12) },
      { id: 'a8', type: 'task_completed', userId: 'u3', targetId: 't4', targetType: 'task', text: 'completed this task', createdAt: daysFromNow(-2) },
    ],
  },
  {
    id: 't5',
    title: 'User testing sessions',
    description: 'Run 5 user testing sessions with the new onboarding prototype.',
    completed: false,
    status: 'todo',
    priority: 'medium',
    backgroundColor: '#f59e0b',
    dueDate: daysFromNow(5),
    createdAt: daysFromNow(-3),
    updatedAt: daysFromNow(-3),
    projectId: 'p1',
    assigneeId: 'u5',
    labelIds: ['l6', 'l1'],
    columnId: 'c2',
    position: 0,
    checklist: [],
    comments: [],
    attachments: [],
    activity: [
      { id: 'a9', type: 'task_created', userId: 'u5', targetId: 't5', targetType: 'task', text: 'created this task', createdAt: daysFromNow(-3) },
    ],
  },
  {
    id: 't6',
    title: 'Push notification system',
    description: 'Add push notifications for task assignments and deadlines.',
    completed: false,
    status: 'backlog',
    priority: 'low',
    backgroundColor: '#64748b',
    createdAt: daysFromNow(-1),
    updatedAt: daysFromNow(-1),
    projectId: 'p1',
    assigneeId: 'u4',
    labelIds: ['l3', 'l5'],
    columnId: 'c1',
    position: 0,
    checklist: [],
    comments: [],
    attachments: [],
    activity: [],
  },
  {
    id: 't7',
    title: 'Dark mode polish',
    description: 'Review every screen in dark mode and fix contrast issues.',
    completed: false,
    status: 'todo',
    priority: 'high',
    backgroundColor: '#8b5cf6',
    dueDate: daysFromNow(4),
    createdAt: daysFromNow(-2),
    updatedAt: daysFromNow(-1),
    projectId: 'p1',
    assigneeId: 'u1',
    labelIds: ['l1', 'l2'],
    columnId: 'c2',
    position: 1,
    checklist: [
      { id: 'ch15', text: 'Dashboard', completed: false },
      { id: 'ch16', text: 'Kanban board', completed: false },
      { id: 'ch17', text: 'Settings', completed: false },
    ],
    comments: [],
    attachments: [],
    activity: [],
  },
  {
    id: 't8',
    title: 'Optimize bundle size',
    description: 'Audit dependencies and reduce the initial JS bundle by 30%.',
    completed: true,
    status: 'done',
    priority: 'medium',
    backgroundColor: '#10b981',
    dueDate: daysFromNow(-5),
    createdAt: daysFromNow(-15),
    updatedAt: daysFromNow(-5),
    projectId: 'p1',
    assigneeId: 'u6',
    labelIds: ['l3'],
    columnId: 'c5',
    position: 1,
    checklist: [
      { id: 'ch18', text: 'Audit deps', completed: true },
      { id: 'ch19', text: 'Tree-shake', completed: true },
    ],
    comments: [],
    attachments: [],
    activity: [],
  },
  {
    id: 't9',
    title: 'Landing page hero animation',
    description: 'Add a subtle parallax animation to the hero section.',
    completed: false,
    status: 'review',
    priority: 'low',
    backgroundColor: '#ec4899',
    dueDate: daysFromNow(2),
    createdAt: daysFromNow(-4),
    updatedAt: daysFromNow(-1),
    projectId: 'p2',
    assigneeId: 'u2',
    labelIds: ['l8', 'l1'],
    columnId: 'c4',
    position: 1,
    checklist: [],
    comments: [],
    attachments: [],
    activity: [],
  },
  {
    id: 't10',
    title: 'Blog CMS integration',
    description: 'Connect the blog to a headless CMS for non-technical authors.',
    completed: false,
    status: 'in_progress',
    priority: 'high',
    backgroundColor: '#3b82f6',
    dueDate: daysFromNow(6),
    createdAt: daysFromNow(-3),
    updatedAt: daysFromNow(-1),
    projectId: 'p2',
    assigneeId: 'u5',
    labelIds: ['l3', 'l5'],
    columnId: 'c3',
    position: 2,
    checklist: [],
    comments: [],
    attachments: [],
    activity: [],
  },
  {
    id: 't11',
    title: 'Competitor analysis report',
    description: 'Analyze 5 competitors and summarize strengths and weaknesses.',
    completed: false,
    status: 'todo',
    priority: 'medium',
    backgroundColor: '#f59e0b',
    dueDate: daysFromNow(7),
    createdAt: daysFromNow(-2),
    updatedAt: daysFromNow(-2),
    projectId: 'p4',
    assigneeId: 'u7',
    labelIds: ['l6'],
    columnId: 'c2',
    position: 2,
    checklist: [],
    comments: [],
    attachments: [],
    activity: [],
  },
  {
    id: 't12',
    title: 'Schedule user interviews',
    description: 'Reach out to 10 customers and schedule 30-min interviews.',
    completed: true,
    status: 'done',
    priority: 'low',
    backgroundColor: '#10b981',
    dueDate: daysFromNow(-1),
    createdAt: daysFromNow(-6),
    updatedAt: daysFromNow(-1),
    projectId: 'p4',
    assigneeId: 'u5',
    labelIds: ['l6'],
    columnId: 'c5',
    position: 2,
    checklist: [],
    comments: [],
    attachments: [],
    activity: [],
  },
];

export const notifications: Notification[] = [
  { id: 'n1', type: 'assignment', title: 'New assignment', message: 'Jordan Lee assigned you "Design new onboarding screens"', read: false, createdAt: daysFromNow(0), userId: 'u2', targetId: 't1', targetType: 'task' },
  { id: 'n2', type: 'deadline', title: 'Deadline approaching', message: '"Implement authentication flow" is due tomorrow', read: false, createdAt: daysFromNow(0), userId: 'u4', targetId: 't2', targetType: 'task' },
  { id: 'n3', type: 'comment', title: 'New comment', message: 'Sam Rivera commented on "Set up CI/CD pipeline"', read: false, createdAt: daysFromNow(-1), userId: 'u3', targetId: 't3', targetType: 'task' },
  { id: 'n4', type: 'invite', title: 'Project invite', message: 'You were invited to join "Brand Refresh"', read: true, createdAt: daysFromNow(-2), userId: 'u1', targetId: 'p6', targetType: 'project' },
  { id: 'n5', type: 'update', title: 'Project updated', message: 'Morgan Patel updated "Marketing Website"', read: true, createdAt: daysFromNow(-3), userId: 'u5', targetId: 'p2', targetType: 'project' },
  { id: 'n6', type: 'mention', title: 'You were mentioned', message: 'Taylor Chen mentioned you in "Dark mode polish"', read: true, createdAt: daysFromNow(-4), userId: 'u4', targetId: 't7', targetType: 'task' },
];

export const recentActivities: Activity[] = [
  baseActivity('task_created', 'u1', 'created "Design new onboarding screens"', 0),
  baseActivity('task_completed', 'u3', 'completed "Write API documentation"', 0),
  baseActivity('project_joined', 'u7', 'joined "Customer Research"', 1),
  baseActivity('project_updated', 'u2', 'updated "Marketing Website"', 1),
  baseActivity('status_changed', 'u6', 'moved "Set up CI/CD pipeline" to Review', 1),
  baseActivity('priority_changed', 'u1', 'changed "Dark mode polish" priority to High', 2),
  baseActivity('assigned', 'u4', 'was assigned "Implement authentication flow"', 2),
  baseActivity('commented', 'u2', 'commented on "Design new onboarding screens"', 3),
];
